import { CampusLocation } from '@/types';

// Reference coordinate: Scaler School of Technology (SST), Electronic City Phase 1, Bangalore (12.8452° N, 77.6602° E)
export const INITIAL_CAMPUS_LOCATIONS: CampusLocation[] = [
  // ==========================================
  // SST BANGALORE (Current Electronic City Campus)
  // ==========================================
  {
    id: 'loc-sst-cafe',
    code: 'SST-CAFE-B1',
    name: 'SST Cafeteria & Brainstorming Hub',
    campus_id: 'sst_bangalore',
    building: 'Main Campus Block',
    floor: 'Basement',
    floor_level: -1,
    type: 'cafeteria',
    description: 'Vibrant student dining hub with espresso bar, food counters, and late-night hackathon brainstorming tables.',
    capacity: 100,
    current_occupancy: 78, // 78% full
    is_quiet: false,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'lively',
    latitude: 12.84518,
    longitude: 77.66015,
    coordinates_x: 240,
    coordinates_y: 350,
    distance_minutes: 2,
    status: 'moderate',
  },
  {
    id: 'loc-sst-rec',
    code: 'SST-REC-B1',
    name: 'Recreation & Indoor Game Zone',
    campus_id: 'sst_bangalore',
    building: 'Main Campus Block',
    floor: 'Basement',
    floor_level: -1,
    type: 'lounge',
    description: 'Breakout area with table tennis, foosball tables, and casual group lounge couches.',
    capacity: 30,
    current_occupancy: 14, // 46% full
    is_quiet: false,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'lively',
    latitude: 12.84519,
    longitude: 77.66025,
    coordinates_x: 680,
    coordinates_y: 350,
    distance_minutes: 2,
    status: 'available',
  },
  {
    id: 'loc-sst-innov-lab',
    code: 'SST-INNOV-G',
    name: 'Flagship Innovation Lab (AI & Robotics)',
    campus_id: 'sst_bangalore',
    building: 'Main Campus Block',
    floor: 'Ground Floor',
    floor_level: 0,
    type: 'lab',
    description: 'Central hardware and AI prototyping hub supporting robotics, drone experiments, and deep-tech startup builds.',
    capacity: 50,
    current_occupancy: 32, // 64% full
    is_quiet: false,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'moderate',
    latitude: 12.84522,
    longitude: 77.66018,
    coordinates_x: 280,
    coordinates_y: 200,
    distance_minutes: 1,
    status: 'available',
  },
  {
    id: 'loc-sst-foyer',
    code: 'SST-FOYER-G',
    name: 'Main Reception & Innovation Foyer',
    campus_id: 'sst_bangalore',
    building: 'Main Campus Block',
    floor: 'Ground Floor',
    floor_level: 0,
    type: 'lounge',
    description: 'High-ceiling welcoming lobby with digital project showcases, visitor desks, and comfortable breakout booths.',
    capacity: 30,
    current_occupancy: 11, // 36% full
    is_quiet: false,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'moderate',
    latitude: 12.84523,
    longitude: 77.66022,
    coordinates_x: 680,
    coordinates_y: 200,
    distance_minutes: 1,
    status: 'available',
  },
  {
    id: 'loc-sst-amphi',
    code: 'SST-AMPHI-101',
    name: '200-Seater Amphitheater Hall',
    campus_id: 'sst_bangalore',
    building: 'Main Campus Block',
    floor: 'Floor 1',
    floor_level: 1,
    type: 'classroom',
    description: 'Tiered auditorium equipped with multi-screens for live coding, guest tech lectures, and masterclasses.',
    capacity: 200,
    current_occupancy: 162, // 81% full
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'quiet',
    latitude: 12.84525,
    longitude: 77.66016,
    coordinates_x: 320,
    coordinates_y: 120,
    distance_minutes: 2,
    status: 'full',
  },
  {
    id: 'loc-sst-class-102',
    code: 'SST-CLASS-102',
    name: 'Interactive Tech Classroom 102',
    campus_id: 'sst_bangalore',
    building: 'Main Campus Block',
    floor: 'Floor 1',
    floor_level: 1,
    type: 'classroom',
    description: 'Live coding classroom with dual 4K laser projectors, ergonomic desks, and collaborative team clusters.',
    capacity: 60,
    current_occupancy: 18, // 30% full (Spacious!)
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'quiet',
    latitude: 12.84526,
    longitude: 77.66024,
    coordinates_x: 720,
    coordinates_y: 120,
    distance_minutes: 2,
    status: 'available',
  },
  {
    id: 'loc-sst-read-room',
    code: 'SST-READ-2F',
    name: 'Quiet Reading Room & Digital Library',
    campus_id: 'sst_bangalore',
    building: 'Main Campus Block',
    floor: 'Floor 2',
    floor_level: 2,
    type: 'library',
    description: 'Strictly silent zone with individual study carrels, acoustic dampening panels, and curated computer science literature.',
    capacity: 40,
    current_occupancy: 10, // 25% full (Spacious!)
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'silent',
    latitude: 12.84528,
    longitude: 77.66014,
    coordinates_x: 220,
    coordinates_y: 240,
    distance_minutes: 3,
    status: 'available',
  },
  {
    id: 'loc-sst-pod-b',
    code: 'SST-POD-B',
    name: 'Coding Pod B (Sprint & Collab Room)',
    campus_id: 'sst_bangalore',
    building: 'Main Campus Block',
    floor: 'Floor 2',
    floor_level: 2,
    type: 'study_room',
    description: 'High-demand group pod with dual magnetic whiteboards, dedicated power outlets at every chair, and video conferencing rig.',
    capacity: 24,
    current_occupancy: 20, // 83% full -> Demo Hero target!
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'quiet',
    latitude: 12.84529,
    longitude: 77.66020,
    coordinates_x: 520,
    coordinates_y: 240,
    distance_minutes: 3,
    status: 'full',
  },
  {
    id: 'loc-sst-nook-a',
    code: 'SST-NOOK-A',
    name: 'Focus Study Nook A',
    campus_id: 'sst_bangalore',
    building: 'Main Campus Block',
    floor: 'Floor 2',
    floor_level: 2,
    type: 'study_room',
    description: 'Private single-seater acoustic focus pods with adjustable lighting and noise-isolation booths.',
    capacity: 16,
    current_occupancy: 4, // 25% full
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'silent',
    latitude: 12.84530,
    longitude: 77.66026,
    coordinates_x: 780,
    coordinates_y: 240,
    distance_minutes: 3,
    status: 'available',
  },
  {
    id: 'loc-sst-hack-arena',
    code: 'SST-HACK-3F',
    name: 'Turing Hackathon Arena & AI Lab',
    campus_id: 'sst_bangalore',
    building: 'Main Campus Block',
    floor: 'Floor 3',
    floor_level: 3,
    type: 'lab',
    description: 'High-power dual-monitor dev stations, GPU servers, Linux/macOS workbenches, and gigabit wired ports.',
    capacity: 45,
    current_occupancy: 12, // 26% full
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'quiet',
    latitude: 12.84532,
    longitude: 77.66016,
    coordinates_x: 320,
    coordinates_y: 180,
    distance_minutes: 4,
    status: 'available',
  },
  {
    id: 'loc-sst-incub-lounge',
    code: 'SST-INCUB-3F',
    name: 'Startup Incubation & Founder Lounge',
    campus_id: 'sst_bangalore',
    building: 'Main Campus Block',
    floor: 'Floor 3',
    floor_level: 3,
    type: 'lounge',
    description: 'Open-concept space for student startup founders with pitch deck presentation screens and bean bags.',
    capacity: 35,
    current_occupancy: 18, // 51% full
    is_quiet: false,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'moderate',
    latitude: 12.84533,
    longitude: 77.66023,
    coordinates_x: 720,
    coordinates_y: 180,
    distance_minutes: 4,
    status: 'available',
  },
  {
    id: 'loc-sst-turf-roof',
    code: 'SST-TURF-ROOF',
    name: 'Rooftop Sports Turf & Breakout Area',
    campus_id: 'sst_bangalore',
    building: 'Main Campus Block',
    floor: 'Rooftop',
    floor_level: 4,
    type: 'lounge',
    description: 'Open-sky all-weather synthetic turf for cricket/football and open-air sunset brainstorming.',
    capacity: 50,
    current_occupancy: 8, // 16% full
    is_quiet: false,
    has_charging: false,
    has_fast_wifi: true,
    noise_level: 'lively',
    latitude: 12.84535,
    longitude: 77.66020,
    coordinates_x: 500,
    coordinates_y: 100,
    distance_minutes: 5,
    status: 'available',
  },

  // ==========================================
  // NEW 20-ACRE SCALER CAMPUS (Future Expansion Preview)
  // ==========================================
  {
    id: 'loc-20ac-lib',
    code: 'SST20-LIB',
    name: 'Grand Central Tech Library (3 Floors)',
    campus_id: 'sst_20acre_new',
    building: 'Academic Block Alpha',
    floor: 'Floor 1-3',
    floor_level: 1,
    type: 'library',
    description: 'Massive 3-story glass atrium library with 500+ private study pods, research archives, and automated checkout.',
    capacity: 500,
    current_occupancy: 120,
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'silent',
    latitude: 12.8350,
    longitude: 77.6520,
    coordinates_x: 250,
    coordinates_y: 200,
    distance_minutes: 6,
    status: 'available',
  },
  {
    id: 'loc-20ac-supercomputer',
    code: 'SST20-AI-LAB',
    name: 'Supercomputing & Quantum AI Hub',
    campus_id: 'sst_20acre_new',
    building: 'Deep-Tech Research Tower',
    floor: 'Floor 2',
    floor_level: 2,
    type: 'lab',
    description: 'Enterprise GPU cluster compute suites with cryogenic cooling labs and multi-monitor developer pods.',
    capacity: 150,
    current_occupancy: 45,
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'quiet',
    latitude: 12.8352,
    longitude: 77.6524,
    coordinates_x: 550,
    coordinates_y: 160,
    distance_minutes: 8,
    status: 'available',
  },
  {
    id: 'loc-20ac-incubator',
    code: 'SST20-UNICORN',
    name: '20-Acre Unicorn Startup Pavilion',
    campus_id: 'sst_20acre_new',
    building: 'Scaler Venture Complex',
    floor: 'Floor 1',
    floor_level: 1,
    type: 'lounge',
    description: 'Venture capital pitching suites, mentor pods, and 24/7 startup hacking lounges.',
    capacity: 250,
    current_occupancy: 95,
    is_quiet: false,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'moderate',
    latitude: 12.8355,
    longitude: 77.6528,
    coordinates_x: 750,
    coordinates_y: 300,
    distance_minutes: 7,
    status: 'available',
  },
  {
    id: 'loc-20ac-audi-1000',
    code: 'SST20-AUDI',
    name: '1000-Seater Global Auditorium',
    campus_id: 'sst_20acre_new',
    building: 'Convention Block',
    floor: 'Ground Floor',
    floor_level: 0,
    type: 'classroom',
    description: 'Flagship university auditorium with broadcast studios, simultaneous translation booths, and Dolby acoustics.',
    capacity: 1000,
    current_occupancy: 350,
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'quiet',
    latitude: 12.8358,
    longitude: 77.6522,
    coordinates_x: 350,
    coordinates_y: 400,
    distance_minutes: 10,
    status: 'available',
  },
];
