import { CampusLocation } from '@/types';

// Strict floor order constant
export const SST_FLOOR_ORDER = ['Upper Basement', 'Ground Floor', 'Floor 1', 'Floor 2'];

// Reference coordinate: Scaler School of Technology (SST), Electronic City Phase 1, Bangalore (12.8452° N, 77.6602° E)
export const INITIAL_CAMPUS_LOCATIONS: CampusLocation[] = [
  // =========================================================================
  // SST BANGALORE (Accurate Real Campus Architecture & Matterport Spatial Scans)
  // =========================================================================

  // -------------------------------------------------------------------------
  // 1. UPPER BASEMENT (Mess Floor: Cheftalk + The Craving Brew & Indoor Play Zone)
  // -------------------------------------------------------------------------
  {
    id: 'loc-sst-chef-c1',
    code: 'SST-CHEF-C1',
    name: 'Cheftalk — Counter 1 (Veg Meals)',
    campus_id: 'sst_bangalore',
    category: 'food',
    building: 'Upper Basement',
    floor: 'Upper Basement',
    floor_level: -1,
    type: 'food_counter',
    description: 'Primary mess counter serving authentic vegetarian daily hot meals, paneer gravies, dal tadka, and fresh phulkas.',
    capacity: 48,
    current_occupancy: 26, // 54% crowd
    table_count: 12,
    mess_provider: 'Cheftalk',
    meal_type: 'Veg',
    is_quiet: false,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'lively',
    latitude: 12.84517,
    longitude: 77.66014,
    coordinates_x: 200,
    coordinates_y: 180,
    distance_minutes: 2,
    status: 'available',
    trend: 'clearing_up',
    wait_time_minutes: 5, // ~5 min wait
    best_time_to_go: 'Right now (Fast-moving token line)',
    peak_hours: '1:00 PM – 2:15 PM & 8:00 PM – 9:15 PM',
    report_count: 19,
    last_reported_minutes_ago: 1,
    confidence: 'high',
    hourly_traffic: [
      { hour: '8 AM', hourNum: 8, occupancyPercentage: 25 },
      { hour: '10 AM', hourNum: 10, occupancyPercentage: 15 },
      { hour: '12 PM', hourNum: 12, occupancyPercentage: 60 },
      { hour: '1 PM', hourNum: 13, occupancyPercentage: 85 },
      { hour: '2 PM', hourNum: 14, occupancyPercentage: 70 },
      { hour: '4 PM', hourNum: 16, occupancyPercentage: 20 },
      { hour: '6 PM', hourNum: 18, occupancyPercentage: 35 },
      { hour: '8 PM', hourNum: 20, occupancyPercentage: 80 },
      { hour: '10 PM', hourNum: 22, occupancyPercentage: 15 },
    ],
  },
  {
    id: 'loc-sst-chef-c2',
    code: 'SST-CHEF-C2',
    name: 'Cheftalk — Counter 2 (Non-Veg Meals)',
    campus_id: 'sst_bangalore',
    category: 'food',
    building: 'Upper Basement',
    floor: 'Upper Basement',
    floor_level: -1,
    type: 'food_counter',
    description: 'Dedicated non-vegetarian mess station serving chicken curry, egg biryani, egg roast, and chef specials.',
    capacity: 48,
    current_occupancy: 32, // 66% crowd
    table_count: 12,
    mess_provider: 'Cheftalk',
    meal_type: 'Non-Veg',
    is_quiet: false,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'lively',
    latitude: 12.84518,
    longitude: 77.66018,
    coordinates_x: 440,
    coordinates_y: 180,
    distance_minutes: 2,
    status: 'available',
    trend: 'steady',
    wait_time_minutes: 6, // ~6 min wait
    best_time_to_go: 'Around 1:45 PM',
    peak_hours: '1:15 PM – 2:30 PM & 8:15 PM – 9:30 PM',
    report_count: 14,
    last_reported_minutes_ago: 2,
    confidence: 'high',
    hourly_traffic: [
      { hour: '8 AM', hourNum: 8, occupancyPercentage: 20 },
      { hour: '10 AM', hourNum: 10, occupancyPercentage: 10 },
      { hour: '12 PM', hourNum: 12, occupancyPercentage: 65 },
      { hour: '1 PM', hourNum: 13, occupancyPercentage: 90 },
      { hour: '2 PM', hourNum: 14, occupancyPercentage: 75 },
      { hour: '4 PM', hourNum: 16, occupancyPercentage: 15 },
      { hour: '6 PM', hourNum: 18, occupancyPercentage: 40 },
      { hour: '8 PM', hourNum: 20, occupancyPercentage: 85 },
      { hour: '10 PM', hourNum: 22, occupancyPercentage: 20 },
    ],
  },
  {
    id: 'loc-sst-chef-jain',
    code: 'SST-CHEF-JAIN',
    name: 'Cheftalk — Counter 3 (Jain Meals)',
    campus_id: 'sst_bangalore',
    category: 'food',
    building: 'Upper Basement',
    floor: 'Upper Basement',
    floor_level: -1,
    type: 'food_counter',
    description: 'Strict pure vegetarian Jain meal station prepared with zero root vegetables (no onion/garlic/potatoes).',
    capacity: 32,
    current_occupancy: 8, // 25% crowd
    table_count: 8,
    mess_provider: 'Cheftalk',
    meal_type: 'Jain',
    is_quiet: false,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'lively',
    latitude: 12.84518,
    longitude: 77.66022,
    coordinates_x: 680,
    coordinates_y: 180,
    distance_minutes: 2,
    status: 'available',
    trend: 'clearing_up',
    wait_time_minutes: 2, // ~2 min wait
    best_time_to_go: 'Open with zero wait queue',
    peak_hours: '1:15 PM – 2:00 PM',
    report_count: 8,
    last_reported_minutes_ago: 3,
    confidence: 'high',
    hourly_traffic: [
      { hour: '8 AM', hourNum: 8, occupancyPercentage: 15 },
      { hour: '10 AM', hourNum: 10, occupancyPercentage: 10 },
      { hour: '12 PM', hourNum: 12, occupancyPercentage: 45 },
      { hour: '1 PM', hourNum: 13, occupancyPercentage: 60 },
      { hour: '2 PM', hourNum: 14, occupancyPercentage: 40 },
      { hour: '4 PM', hourNum: 16, occupancyPercentage: 10 },
      { hour: '6 PM', hourNum: 18, occupancyPercentage: 25 },
      { hour: '8 PM', hourNum: 20, occupancyPercentage: 55 },
      { hour: '10 PM', hourNum: 22, occupancyPercentage: 10 },
    ],
  },
  {
    id: 'loc-sst-craving-brew',
    code: 'SST-FOOD-BREW',
    name: 'The Craving Brew (Alternate Mess Provider)',
    campus_id: 'sst_bangalore',
    category: 'food',
    building: 'Upper Basement',
    floor: 'Upper Basement',
    floor_level: -1,
    type: 'cafeteria',
    description: 'Official alternate student mess provider serving daily wholesome thalis, curated combo meals, executive meal platters, and hot sides.',
    capacity: 32,
    current_occupancy: 25, // 78% crowd (High demand)
    table_count: 10,
    mess_provider: 'The Craving Brew',
    meal_type: 'Alternate Mess Meal',
    is_quiet: false,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'lively',
    latitude: 12.84519,
    longitude: 77.66026,
    coordinates_x: 880,
    coordinates_y: 180,
    distance_minutes: 2,
    status: 'full',
    trend: 'getting_busier',
    wait_time_minutes: 10, // ~10 min wait
    best_time_to_go: 'Around 2:15 PM (Post peak lunch wave)',
    peak_hours: '1:00 PM – 2:15 PM & 8:00 PM – 9:30 PM',
    report_count: 18,
    last_reported_minutes_ago: 1,
    confidence: 'high',
    hourly_traffic: [
      { hour: '8 AM', hourNum: 8, occupancyPercentage: 30 },
      { hour: '10 AM', hourNum: 10, occupancyPercentage: 25 },
      { hour: '12 PM', hourNum: 12, occupancyPercentage: 70 },
      { hour: '1 PM', hourNum: 13, occupancyPercentage: 92 },
      { hour: '2 PM', hourNum: 14, occupancyPercentage: 80 },
      { hour: '4 PM', hourNum: 16, occupancyPercentage: 35 },
      { hour: '6 PM', hourNum: 18, occupancyPercentage: 50 },
      { hour: '8 PM', hourNum: 20, occupancyPercentage: 88 },
      { hour: '10 PM', hourNum: 22, occupancyPercentage: 30 },
    ],
  },
  {
    id: 'loc-sst-play-zone',
    code: 'SST-PLAY-ZONE',
    name: 'Play Zone & Indoor Games (Basement)',
    campus_id: 'sst_bangalore',
    category: 'sports',
    building: 'Upper Basement',
    floor: 'Upper Basement',
    floor_level: -1,
    type: 'lounge',
    description: 'Basement recreation lounge with table tennis, foosball tables, and student chill couches.',
    capacity: 24,
    current_occupancy: 10, // 41% full
    table_count: 6,
    is_quiet: false,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'lively',
    latitude: 12.84520,
    longitude: 77.66020,
    coordinates_x: 500,
    coordinates_y: 380,
    distance_minutes: 2,
    status: 'available',
    trend: 'steady',
    best_time_to_go: 'Evening breakout (Post 6:30 PM)',
    peak_hours: '1:00 PM – 3:00 PM & 7:00 PM – 9:00 PM',
    report_count: 9,
    last_reported_minutes_ago: 4,
    confidence: 'high',
    equipment_items: [
      { name: 'Table Tennis Paddles', available: 4, total: 6 },
      { name: 'Foosballs', available: 2, total: 2 },
    ],
    hourly_traffic: [
      { hour: '8 AM', hourNum: 8, occupancyPercentage: 10 },
      { hour: '10 AM', hourNum: 10, occupancyPercentage: 10 },
      { hour: '12 PM', hourNum: 12, occupancyPercentage: 40 },
      { hour: '1 PM', hourNum: 13, occupancyPercentage: 65 },
      { hour: '2 PM', hourNum: 14, occupancyPercentage: 55 },
      { hour: '4 PM', hourNum: 16, occupancyPercentage: 35 },
      { hour: '6 PM', hourNum: 18, occupancyPercentage: 75 },
      { hour: '8 PM', hourNum: 20, occupancyPercentage: 80 },
      { hour: '10 PM', hourNum: 22, occupancyPercentage: 40 },
    ],
  },

  // -------------------------------------------------------------------------
  // 2. GROUND FLOOR (Academic Study & Outdoor Sports Zone)
  // -------------------------------------------------------------------------
  // Academic Study Row (y: 160)
  {
    id: 'loc-sst-g-classroom',
    code: 'SST-G-CLASS',
    name: 'Ground Floor Tech Classroom',
    campus_id: 'sst_bangalore',
    category: 'study',
    building: 'Main Academic Block',
    floor: 'Ground Floor',
    floor_level: 0,
    type: 'classroom',
    description: 'Main lecture and workshop hall with dual laser projectors, tiered desks, and heavy-duty power rails.',
    capacity: 60,
    current_occupancy: 20, // 33% full (Spacious)
    table_count: 15,
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'quiet',
    latitude: 12.84522,
    longitude: 77.66018,
    coordinates_x: 320,
    coordinates_y: 160,
    distance_minutes: 1,
    status: 'available',
    trend: 'clearing_up',
    best_time_to_go: 'Post 4:00 PM (After day lectures)',
    peak_hours: '10:00 AM – 3:30 PM',
    report_count: 10,
    last_reported_minutes_ago: 3,
    confidence: 'high',
    hourly_traffic: [
      { hour: '8 AM', hourNum: 8, occupancyPercentage: 15 },
      { hour: '10 AM', hourNum: 10, occupancyPercentage: 75 },
      { hour: '12 PM', hourNum: 12, occupancyPercentage: 80 },
      { hour: '1 PM', hourNum: 13, occupancyPercentage: 60 },
      { hour: '2 PM', hourNum: 14, occupancyPercentage: 85 },
      { hour: '4 PM', hourNum: 16, occupancyPercentage: 35 },
      { hour: '6 PM', hourNum: 18, occupancyPercentage: 25 },
      { hour: '8 PM', hourNum: 20, occupancyPercentage: 20 },
      { hour: '10 PM', hourNum: 22, occupancyPercentage: 10 },
    ],
  },
  {
    id: 'loc-sst-g-reading',
    code: 'SST-G-READ',
    name: 'Ground Floor Reading Area',
    campus_id: 'sst_bangalore',
    category: 'study',
    building: 'Main Academic Block',
    floor: 'Ground Floor',
    floor_level: 0,
    type: 'library',
    description: 'Quiet study tables near the main lobby with natural lighting, ergonomic chairs, and task lamps.',
    capacity: 32,
    current_occupancy: 10, // 31% full
    table_count: 8,
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'silent',
    latitude: 12.84524,
    longitude: 77.66022,
    coordinates_x: 680,
    coordinates_y: 160,
    distance_minutes: 1,
    status: 'available',
    trend: 'steady',
    best_time_to_go: 'Open all morning (8:00 AM – 1:00 PM)',
    peak_hours: '2:00 PM – 5:00 PM',
    report_count: 8,
    last_reported_minutes_ago: 4,
    confidence: 'high',
    hourly_traffic: [
      { hour: '8 AM', hourNum: 8, occupancyPercentage: 20 },
      { hour: '10 AM', hourNum: 10, occupancyPercentage: 30 },
      { hour: '12 PM', hourNum: 12, occupancyPercentage: 45 },
      { hour: '1 PM', hourNum: 13, occupancyPercentage: 55 },
      { hour: '2 PM', hourNum: 14, occupancyPercentage: 75 },
      { hour: '4 PM', hourNum: 16, occupancyPercentage: 65 },
      { hour: '6 PM', hourNum: 18, occupancyPercentage: 40 },
      { hour: '8 PM', hourNum: 20, occupancyPercentage: 30 },
      { hour: '10 PM', hourNum: 22, occupancyPercentage: 15 },
    ],
  },

  // Outdoor Sports Row (y: 360)
  {
    id: 'loc-sst-turf-ground',
    code: 'SST-TURF-OUT',
    name: 'Turff Ground (Football & Box Cricket)',
    campus_id: 'sst_bangalore',
    category: 'sports',
    building: 'Outdoor Sports Zone',
    floor: 'Ground Floor',
    floor_level: 0,
    type: 'sports_court',
    description: 'Enclosed synthetic turf for 5v5 football matches, box cricket tournaments, and sprint drills.',
    capacity: 20,
    current_occupancy: 4, // 20% full
    table_count: 4,
    is_quiet: false,
    has_charging: false,
    has_fast_wifi: true,
    noise_level: 'lively',
    latitude: 12.84534,
    longitude: 77.66014,
    coordinates_x: 220,
    coordinates_y: 360,
    distance_minutes: 2,
    status: 'available',
    trend: 'steady',
    best_time_to_go: 'Open right now (Sunset slot open)',
    peak_hours: '5:00 PM – 8:30 PM',
    report_count: 11,
    last_reported_minutes_ago: 4,
    confidence: 'high',
    equipment_items: [
      { name: 'Footballs', available: 3, total: 5 },
      { name: 'Cricket Kits', available: 2, total: 3 },
    ],
    hourly_traffic: [
      { hour: '8 AM', hourNum: 8, occupancyPercentage: 25 },
      { hour: '10 AM', hourNum: 10, occupancyPercentage: 10 },
      { hour: '12 PM', hourNum: 12, occupancyPercentage: 5 },
      { hour: '1 PM', hourNum: 13, occupancyPercentage: 5 },
      { hour: '2 PM', hourNum: 14, occupancyPercentage: 10 },
      { hour: '4 PM', hourNum: 16, occupancyPercentage: 35 },
      { hour: '6 PM', hourNum: 18, occupancyPercentage: 85 },
      { hour: '8 PM', hourNum: 20, occupancyPercentage: 80 },
      { hour: '10 PM', hourNum: 22, occupancyPercentage: 30 },
    ],
  },
  {
    id: 'loc-sst-badminton-court',
    code: 'SST-BADMINTON-OUT',
    name: 'Badminton & Volleyball Court',
    campus_id: 'sst_bangalore',
    category: 'sports',
    building: 'Outdoor Sports Zone',
    floor: 'Ground Floor',
    floor_level: 0,
    type: 'sports_court',
    description: 'Professional synthetic dual-use court for badminton singles/doubles and volleyball matches.',
    capacity: 12,
    current_occupancy: 2, // 16% full
    table_count: 2,
    is_quiet: false,
    has_charging: false,
    has_fast_wifi: true,
    noise_level: 'lively',
    latitude: 12.84535,
    longitude: 77.66018,
    coordinates_x: 500,
    coordinates_y: 360,
    distance_minutes: 2,
    status: 'available',
    trend: 'steady',
    best_time_to_go: 'Early mornings (6:30 AM - 9:00 AM)',
    peak_hours: '5:30 PM – 8:00 PM',
    report_count: 7,
    last_reported_minutes_ago: 5,
    confidence: 'high',
    equipment_items: [
      { name: 'Badminton Rackets', available: 6, total: 8 },
      { name: 'Volleyballs', available: 2, total: 3 },
    ],
    hourly_traffic: [
      { hour: '8 AM', hourNum: 8, occupancyPercentage: 40 },
      { hour: '10 AM', hourNum: 10, occupancyPercentage: 15 },
      { hour: '12 PM', hourNum: 12, occupancyPercentage: 10 },
      { hour: '1 PM', hourNum: 13, occupancyPercentage: 10 },
      { hour: '2 PM', hourNum: 14, occupancyPercentage: 15 },
      { hour: '4 PM', hourNum: 16, occupancyPercentage: 40 },
      { hour: '6 PM', hourNum: 18, occupancyPercentage: 80 },
      { hour: '8 PM', hourNum: 20, occupancyPercentage: 75 },
      { hour: '10 PM', hourNum: 22, occupancyPercentage: 20 },
    ],
  },
  {
    id: 'loc-sst-basketball-court',
    code: 'SST-BASKETBALL-OUT',
    name: 'Basketball Court',
    campus_id: 'sst_bangalore',
    category: 'sports',
    building: 'Outdoor Sports Zone',
    floor: 'Ground Floor',
    floor_level: 0,
    type: 'sports_court',
    description: 'Full-sized outdoor acrylic hardcourt with standard hoops, floodlights, and side bleachers.',
    capacity: 16,
    current_occupancy: 6, // 37% full
    table_count: 3,
    is_quiet: false,
    has_charging: false,
    has_fast_wifi: true,
    noise_level: 'lively',
    latitude: 12.84536,
    longitude: 77.66024,
    coordinates_x: 780,
    coordinates_y: 360,
    distance_minutes: 2,
    status: 'available',
    trend: 'getting_busier',
    best_time_to_go: 'Before 5:30 PM',
    peak_hours: '5:30 PM – 9:00 PM',
    report_count: 10,
    last_reported_minutes_ago: 2,
    confidence: 'high',
    equipment_items: [
      { name: 'Basketballs', available: 6, total: 8 },
    ],
    hourly_traffic: [
      { hour: '8 AM', hourNum: 8, occupancyPercentage: 30 },
      { hour: '10 AM', hourNum: 10, occupancyPercentage: 15 },
      { hour: '12 PM', hourNum: 12, occupancyPercentage: 10 },
      { hour: '1 PM', hourNum: 13, occupancyPercentage: 15 },
      { hour: '2 PM', hourNum: 14, occupancyPercentage: 20 },
      { hour: '4 PM', hourNum: 16, occupancyPercentage: 45 },
      { hour: '6 PM', hourNum: 18, occupancyPercentage: 85 },
      { hour: '8 PM', hourNum: 20, occupancyPercentage: 80 },
      { hour: '10 PM', hourNum: 22, occupancyPercentage: 25 },
    ],
  },

  // -------------------------------------------------------------------------
  // 3. 1ST FLOOR (Block B, Indoor Reading, Outside Terrace Reading)
  // -------------------------------------------------------------------------
  {
    id: 'loc-sst-1f-blockb',
    code: 'SST-1F-BLKB',
    name: 'Block B Innovation & Coding Lab',
    campus_id: 'sst_bangalore',
    category: 'study',
    building: 'Main Academic Block',
    floor: 'Floor 1',
    floor_level: 1,
    type: 'lab',
    description: 'Collaborative development wing with whiteboard walls, dual-screen setups, and high-performance developer workbenches.',
    capacity: 48,
    current_occupancy: 36, // 75% full (High demand)
    table_count: 12,
    is_quiet: false,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'moderate',
    latitude: 12.84525,
    longitude: 77.66016,
    coordinates_x: 240,
    coordinates_y: 260,
    distance_minutes: 2,
    status: 'full',
    trend: 'getting_busier',
    best_time_to_go: 'Around 6:30 PM (Evening sprint)',
    peak_hours: '11:30 AM – 5:00 PM',
    report_count: 15,
    last_reported_minutes_ago: 2,
    confidence: 'high',
    hourly_traffic: [
      { hour: '8 AM', hourNum: 8, occupancyPercentage: 25 },
      { hour: '10 AM', hourNum: 10, occupancyPercentage: 55 },
      { hour: '12 PM', hourNum: 12, occupancyPercentage: 80 },
      { hour: '1 PM', hourNum: 13, occupancyPercentage: 85 },
      { hour: '2 PM', hourNum: 14, occupancyPercentage: 90 },
      { hour: '4 PM', hourNum: 16, occupancyPercentage: 75 },
      { hour: '6 PM', hourNum: 18, occupancyPercentage: 60 },
      { hour: '8 PM', hourNum: 20, occupancyPercentage: 50 },
      { hour: '10 PM', hourNum: 22, occupancyPercentage: 30 },
    ],
  },
  {
    id: 'loc-sst-1f-reading',
    code: 'SST-1F-READ',
    name: 'Floor 1 Indoor Reading Area',
    campus_id: 'sst_bangalore',
    category: 'study',
    building: 'Main Academic Block',
    floor: 'Floor 1',
    floor_level: 1,
    type: 'library',
    description: 'Acoustic-paneled deep-work reading zone dedicated to quiet problem solving and thesis work.',
    capacity: 40,
    current_occupancy: 10, // 25% full (Top Study Match)
    table_count: 10,
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'silent',
    latitude: 12.84526,
    longitude: 77.66020,
    coordinates_x: 500,
    coordinates_y: 260,
    distance_minutes: 2,
    status: 'available',
    trend: 'clearing_up',
    best_time_to_go: 'Right now (Plenty of free carrels)',
    peak_hours: '1:30 PM – 4:00 PM',
    report_count: 12,
    last_reported_minutes_ago: 1,
    confidence: 'high',
    hourly_traffic: [
      { hour: '8 AM', hourNum: 8, occupancyPercentage: 15 },
      { hour: '10 AM', hourNum: 10, occupancyPercentage: 35 },
      { hour: '12 PM', hourNum: 12, occupancyPercentage: 55 },
      { hour: '1 PM', hourNum: 13, occupancyPercentage: 70 },
      { hour: '2 PM', hourNum: 14, occupancyPercentage: 65 },
      { hour: '4 PM', hourNum: 16, occupancyPercentage: 50 },
      { hour: '6 PM', hourNum: 18, occupancyPercentage: 45 },
      { hour: '8 PM', hourNum: 20, occupancyPercentage: 35 },
      { hour: '10 PM', hourNum: 22, occupancyPercentage: 20 },
    ],
  },
  {
    id: 'loc-sst-1f-outside-reading',
    code: 'SST-1F-OUTREAD',
    name: 'Outside Terrace Reading Area',
    campus_id: 'sst_bangalore',
    category: 'study',
    building: 'Main Academic Block',
    floor: 'Floor 1',
    floor_level: 1,
    type: 'study_room',
    description: 'Open-air shaded terrace study space with breeze, comfortable wooden tables, and power strips.',
    capacity: 24,
    current_occupancy: 6, // 25% full
    table_count: 6,
    is_quiet: false,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'quiet',
    latitude: 12.84527,
    longitude: 77.66024,
    coordinates_x: 760,
    coordinates_y: 260,
    distance_minutes: 2,
    status: 'available',
    trend: 'steady',
    best_time_to_go: 'Late afternoons (Cool shade)',
    peak_hours: '12:00 PM – 2:30 PM',
    report_count: 7,
    last_reported_minutes_ago: 4,
    confidence: 'high',
    hourly_traffic: [
      { hour: '8 AM', hourNum: 8, occupancyPercentage: 20 },
      { hour: '10 AM', hourNum: 10, occupancyPercentage: 25 },
      { hour: '12 PM', hourNum: 12, occupancyPercentage: 60 },
      { hour: '1 PM', hourNum: 13, occupancyPercentage: 70 },
      { hour: '2 PM', hourNum: 14, occupancyPercentage: 55 },
      { hour: '4 PM', hourNum: 16, occupancyPercentage: 40 },
      { hour: '6 PM', hourNum: 18, occupancyPercentage: 35 },
      { hour: '8 PM', hourNum: 20, occupancyPercentage: 20 },
      { hour: '10 PM', hourNum: 22, occupancyPercentage: 10 },
    ],
  },

  // -------------------------------------------------------------------------
  // 4. 2ND FLOOR (2A, 2B, 2C)
  // -------------------------------------------------------------------------
  {
    id: 'loc-sst-2f-2a',
    code: 'SST-2F-2A',
    name: 'Classroom & Coding Pod 2A',
    campus_id: 'sst_bangalore',
    category: 'study',
    building: 'Main Academic Block',
    floor: 'Floor 2',
    floor_level: 2,
    type: 'classroom',
    description: 'Dedicated batch classroom and problem-solving hub with team cluster pods.',
    capacity: 40,
    current_occupancy: 12, // 30% full
    table_count: 10,
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'quiet',
    latitude: 12.84528,
    longitude: 77.66014,
    coordinates_x: 240,
    coordinates_y: 260,
    distance_minutes: 3,
    status: 'available',
    trend: 'clearing_up',
    best_time_to_go: 'Post 5:00 PM',
    peak_hours: '10:00 AM – 3:30 PM',
    report_count: 9,
    last_reported_minutes_ago: 2,
    confidence: 'high',
    hourly_traffic: [
      { hour: '8 AM', hourNum: 8, occupancyPercentage: 15 },
      { hour: '10 AM', hourNum: 10, occupancyPercentage: 65 },
      { hour: '12 PM', hourNum: 12, occupancyPercentage: 75 },
      { hour: '1 PM', hourNum: 13, occupancyPercentage: 50 },
      { hour: '2 PM', hourNum: 14, occupancyPercentage: 80 },
      { hour: '4 PM', hourNum: 16, occupancyPercentage: 40 },
      { hour: '6 PM', hourNum: 18, occupancyPercentage: 30 },
      { hour: '8 PM', hourNum: 20, occupancyPercentage: 20 },
      { hour: '10 PM', hourNum: 22, occupancyPercentage: 10 },
    ],
  },
  {
    id: 'loc-sst-2f-2b',
    code: 'SST-2F-2B',
    name: 'Classroom & Coding Pod 2B',
    campus_id: 'sst_bangalore',
    category: 'study',
    building: 'Main Academic Block',
    floor: 'Floor 2',
    floor_level: 2,
    type: 'classroom',
    description: 'Sprint room with 4K screens, magnetic whiteboards, and power outlets at every seat.',
    capacity: 40,
    current_occupancy: 34, // 85% full (Hero Alert Target!)
    table_count: 10,
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'quiet',
    latitude: 12.84529,
    longitude: 77.66020,
    coordinates_x: 500,
    coordinates_y: 260,
    distance_minutes: 3,
    status: 'full',
    trend: 'getting_busier',
    best_time_to_go: 'Around 6:15 PM (Expected ~45%)',
    peak_hours: '11:00 AM – 5:30 PM',
    report_count: 16,
    last_reported_minutes_ago: 1,
    confidence: 'high',
    hourly_traffic: [
      { hour: '8 AM', hourNum: 8, occupancyPercentage: 20 },
      { hour: '10 AM', hourNum: 10, occupancyPercentage: 70 },
      { hour: '12 PM', hourNum: 12, occupancyPercentage: 85 },
      { hour: '1 PM', hourNum: 13, occupancyPercentage: 60 },
      { hour: '2 PM', hourNum: 14, occupancyPercentage: 90 },
      { hour: '4 PM', hourNum: 16, occupancyPercentage: 70 },
      { hour: '6 PM', hourNum: 18, occupancyPercentage: 45 },
      { hour: '8 PM', hourNum: 20, occupancyPercentage: 30 },
      { hour: '10 PM', hourNum: 22, occupancyPercentage: 15 },
    ],
  },
  {
    id: 'loc-sst-2f-2c',
    code: 'SST-2F-2C',
    name: 'Classroom & Coding Pod 2C',
    campus_id: 'sst_bangalore',
    category: 'study',
    building: 'Main Academic Block',
    floor: 'Floor 2',
    floor_level: 2,
    type: 'classroom',
    description: 'Tech seminar and hack room with modular movable tables for group sprint hacking.',
    capacity: 40,
    current_occupancy: 16, // 40% full
    table_count: 10,
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'quiet',
    latitude: 12.84530,
    longitude: 77.66026,
    coordinates_x: 760,
    coordinates_y: 260,
    distance_minutes: 3,
    status: 'available',
    trend: 'steady',
    best_time_to_go: 'Early mornings & evenings',
    peak_hours: '2:00 PM – 4:30 PM',
    report_count: 8,
    last_reported_minutes_ago: 3,
    confidence: 'high',
    hourly_traffic: [
      { hour: '8 AM', hourNum: 8, occupancyPercentage: 15 },
      { hour: '10 AM', hourNum: 10, occupancyPercentage: 55 },
      { hour: '12 PM', hourNum: 12, occupancyPercentage: 65 },
      { hour: '1 PM', hourNum: 13, occupancyPercentage: 45 },
      { hour: '2 PM', hourNum: 14, occupancyPercentage: 70 },
      { hour: '4 PM', hourNum: 16, occupancyPercentage: 40 },
      { hour: '6 PM', hourNum: 18, occupancyPercentage: 30 },
      { hour: '8 PM', hourNum: 20, occupancyPercentage: 20 },
      { hour: '10 PM', hourNum: 22, occupancyPercentage: 10 },
    ],
  },

  // =========================================================================
  // NEW 20-ACRE SCALER CAMPUS (Future Expansion Preview)
  // =========================================================================
  {
    id: 'loc-20ac-lib',
    code: 'SST20-LIB',
    name: 'Grand Central Tech Library (3 Floors)',
    campus_id: 'sst_20acre_new',
    category: 'study',
    building: 'Academic Block Alpha',
    floor: 'Floor 1-3',
    floor_level: 1,
    type: 'library',
    description: 'Massive 3-story glass atrium library with 500+ private study pods, research archives, and automated checkout.',
    capacity: 500,
    current_occupancy: 120,
    table_count: 100,
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'silent',
    latitude: 12.8350,
    longitude: 77.6520,
    coordinates_x: 250,
    coordinates_y: 260,
    distance_minutes: 6,
    status: 'available',
    trend: 'steady',
    best_time_to_go: 'Always spacious (<30%)',
    peak_hours: '2:00 PM – 6:00 PM',
    report_count: 45,
    last_reported_minutes_ago: 1,
    confidence: 'high',
  },
  {
    id: 'loc-20ac-supercomputer',
    code: 'SST20-AI-LAB',
    name: 'Supercomputing & Quantum AI Hub',
    campus_id: 'sst_20acre_new',
    category: 'study',
    building: 'Deep-Tech Research Tower',
    floor: 'Floor 2',
    floor_level: 2,
    type: 'lab',
    description: 'Enterprise GPU cluster compute suites with cryogenic cooling labs and multi-monitor developer pods.',
    capacity: 150,
    current_occupancy: 45,
    table_count: 30,
    is_quiet: true,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'quiet',
    latitude: 12.8352,
    longitude: 77.6524,
    coordinates_x: 500,
    coordinates_y: 260,
    distance_minutes: 8,
    status: 'available',
    trend: 'getting_busier',
    best_time_to_go: 'Morning compute hours (8 AM - 12 PM)',
    peak_hours: '3:00 PM – 9:00 PM',
    report_count: 22,
    last_reported_minutes_ago: 5,
    confidence: 'high',
  },
  {
    id: 'loc-20ac-incubator',
    code: 'SST20-UNICORN',
    name: '20-Acre Unicorn Startup Pavilion',
    campus_id: 'sst_20acre_new',
    category: 'study',
    building: 'Scaler Venture Complex',
    floor: 'Floor 1',
    floor_level: 1,
    type: 'lounge',
    description: 'Venture capital pitching suites, mentor pods, and 24/7 startup hacking lounges.',
    capacity: 250,
    current_occupancy: 95,
    table_count: 50,
    is_quiet: false,
    has_charging: true,
    has_fast_wifi: true,
    noise_level: 'moderate',
    latitude: 12.8355,
    longitude: 77.6528,
    coordinates_x: 750,
    coordinates_y: 260,
    distance_minutes: 7,
    status: 'available',
    trend: 'clearing_up',
    best_time_to_go: 'After 5:00 PM',
    peak_hours: '1:00 PM – 4:00 PM',
    report_count: 18,
    last_reported_minutes_ago: 3,
    confidence: 'high',
  },
];
